sudo: required

language: java

services:
  - docker
  
branches:
  only:
    - master
    - stable

install: true

script:
  - ./gradlew assemble test -i
  #- ./docker-build.sh $TRAVIS_COMMIT $TRAVIS_BUILD_NUMBER

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew pushDockerImages
    on:
      branch: master
