FROM adoptopenjdk/openjdk11:alpine-slim

EXPOSE 8080

WORKDIR /home/ili2gpkg

COPY build/libs/ili2gpkg-web-service-micronaut-*.jar app.jar

RUN chown -R 1001:0 /home/ili2gpkg && \
    chmod -R g=u /home/ili2gpkg

USER 1001

CMD java -noverify -XX:TieredStopAtLevel=1 -Dcom.sun.management.jmxremote -jar app.jar